import "./globals.css";
import type { Metadata } from "next";
import { Sintony, Poppins } from "next/font/google";
import { Header } from "@/components/shared/Header";
import { Main } from "@/components/core/Main/Main";

const sintony = Sintony({
  subsets: ["latin"],
  weight: "700",
  variable: "--font-sintony",
});
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Synced",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${sintony.variable} ${poppins.variable}`}>
      <body>
        <Main bg="stone.50">
          <Header />
          {children}
        </Main>
      </body>
    </html>
  );
}
