import "./globals.css";
import type { Metadata } from "next";
import { Russo_One, Sintony } from "next/font/google";
import { Navigation } from "@/components/shared/Navigation";

const russoOne = Russo_One({ subsets: ["latin"], weight: "400" });
const sintony = Sintony({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Syncity",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${russoOne.variable} ${sintony.variable}`}>
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
