import "./globals.css";
import type { Metadata } from "next";
import { Russo_One, Sintony } from "next/font/google";

const russoOne = Russo_One({ subsets: ["latin"], weight: "400" });
const sintony = Sintony({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Syncity",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${russoOne.className} ${sintony.className}`}>
      <body>{children}</body>
    </html>
  );
}
