import { toastAnatomy } from '@ark-ui/react/anatomy';
import { defineSlotRecipe } from '@pandacss/dev';

export const toast = defineSlotRecipe({
  className: 'toast',
  slots: toastAnatomy.keys(),
  base: {
    group: {
      display: 'flex',
      flexDirection: 'column',
      gap: '3',
      maxWidth: 'sm',
      width: 'full',
      p: '4',
      zIndex: 'toast',
    },
    root: {
      alignItems: 'start',
      background: 'bg.default',
      borderWidth: '1px',
      borderColor: 'border.default',
      borderRadius: 'l4',
      boxShadow: 'lg',
      '&[data-type=success]': { backgroundColor: 'success.muted' },
      '&[data-type=error]': { backgroundColor: 'danger.muted' },
      '&[data-type=warning]': { backgroundColor: 'warning.muted' },
      '&[data-type=info]': { backgroundColor: 'info.muted' },
      '&[data-type=loading]': { backgroundColor: 'bg.muted' },
      '&[data-type=success] svg': { color: 'success.default' },
      '&[data-type=error] svg': { color: 'danger.default' },
      '&[data-type=warning] svg': { color: 'warning.default' },
      '&[data-type=info] svg': { color: 'info.default' },
      display: 'flex',
      gap: '4',
      height: 'var(--height)',
      minWidth: 'xs',
      opacity: 'var(--opacity)',
      overflowWrap: 'anywhere',
      p: '4',
      position: 'relative',
      scale: 'var(--scale)',
      transitionDuration: 'slow',
      transitionProperty: 'translate, scale, opacity, height',
      transitionTimingFunction: 'default',
      translate: 'var(--x) var(--y)',
      width: 'full',
      willChange: 'translate, opacity, scale',
      zIndex: 'var(--z-index)',
    },
    title: {
      color: 'fg.default',
      '[data-type=success] &': { color: 'success.default' },
      '[data-type=error] &': { color: 'danger.default' },
      '[data-type=warning] &': { color: 'warning.default' },
      '[data-type=info] &': { color: 'info.default' },
      fontWeight: 'medium',
      textStyle: 'sm',
    },
    description: {
      color: 'fg.muted',
      textStyle: 'sm',
    },
    actionTrigger: {
      '[data-type=success] &': { color: 'success.default' },
      '[data-type=error] &': { color: 'danger.default' },
      '[data-type=warning] &': { color: 'warning.default' },
      '[data-type=info] &': { color: 'info.default' },
      cursor: 'pointer',
      fontWeight: 'semibold',
      textStyle: 'sm',
    },
    closeTrigger: {
      position: 'absolute',
      top: '2',
      insetEnd: '2',
    },
  },
});
